In [1]:
import pandas as pd
import numpy as np
stats = pd.read_json('MLS_stats_final.json')
salary = pd.read_csv('salaries.csv')

In [2]:
stats = stats[stats['Club'] != '-']
stats = stats.sort_values(by = ['url', 'Year'])
stats = stats.dropna()
stats.shape

(9715, 14)

In [3]:
salary['url'] = salary['urls']
urls = salary['url']
salary.head().T

,0,1,2,3,4
season,2018,2018,2018,2018,2018
club_grouped,TFC,TFC,LAFC,CHI,LAG
club,TOR,TOR,LAFC,CHI,LA
first_name,Sebastian,Michael,Carlos,Bastian,Giovani
last_name,Giovinco,Bradley,Vela,Schweinsteiger,dos Santos
position,F,M,F,M,F
total_compensation,"$7,115,556","$6,500,000","$6,292,500","$6,100,000","$6,000,000"
base_salary,"$5,600,000","$6,000,000","$4,500,000","$6,100,000","$4,250,000"
first_name_cleaned,sebastian,michael,carlos,bastian,giovani
last_name_cleaned,giovinco,bradley,vela,schweinsteiger,dos-santos
urls,https://www.mlssoccer.com/players/sebastian-gi...,https://www.mlssoccer.com/players/michael-bradley,https://www.mlssoccer.com/players/carlos-vela,https://www.mlssoccer.com/players/bastian-schw...,https://www.mlssoccer.com/players/giovani-dos-...
url,https://www.mlssoccer.com/players/sebastian-gi...,https://www.mlssoccer.com/players/michael-bradley,https://www.mlssoccer.com/players/carlos-vela,https://www.mlssoccer.com/players/bastian-schw...,https://www.mlssoccer.com/players/giovani-dos-...

In [4]:
non_aggregate_cols = ['Year', 'Club', 'url']
aggregate_cols = [cols for cols in stats.columns if cols not in non_aggregate_cols]
import numpy as np
stats_aggregate = stats.groupby(non_aggregate_cols).agg(np.sum).reset_index()

In [5]:
stats_aggregate.shape

(6514, 14)

In [6]:
stats.shape

(9715, 14)

In [7]:
stats_aggregate['previous_year'] = stats_aggregate['Year'].astype(int)

In [8]:
salary['previous_year'] = salary['season'] - 1
df = pd.merge(stats_aggregate, salary, on= ['previous_year', 'url'])

In [9]:
df.head().T

,0,1,2,3,4
Year,2006,2006,2006,2006,2006
Club,Chicago Fire,Chicago Fire,Chicago Fire,Chicago Fire,Chicago Fire
url,https://www.mlssoccer.com/players/andy-herron,https://www.mlssoccer.com/players/brian-plotkin,https://www.mlssoccer.com/players/calen-carr,https://www.mlssoccer.com/players/chad-barrett,https://www.mlssoccer.com/players/chris-armas
A,1,1,1,1,5
FC,31,10,21,16,37
G,9,1,1,5,1
GP,22,14,24,16,29
GS,20,4,3,9,29
MINS,1647,526,520,778,2576
OFF,36,1,4,12,0
R,0,0,1,0,0
SHTS,39,14,13,26,22
SOG,26,4,8,14,6
Y,4,2,3,2,5
previous_year,2006,2006,2006,2006,2006
season,2007,2007,2007,2007,2007
club_grouped,CLB,CHI,CHI,CHI,CHI
club,CLB,CHI,CHI,CHI,CHI
first_name,Andy,Brian,Calen,Chad,Chris
last_name,Herron,Plotkin,Carr,Barrett,Armas
position,F,M,F,F,M
total_compensation,"$148,750","$30,000","$50,500","$48,713","$225,000"
base_salary,"$140,000","$30,000","$38,000","$41,213","$225,000"
first_name_cleaned,andy,brian,calen,chad,chris
last_name_cleaned,herron,plotkin,carr,barrett,armas
urls,https://www.mlssoccer.com/players/andy-herron,https://www.mlssoccer.com/players/brian-plotkin,https://www.mlssoccer.com/players/calen-carr,https://www.mlssoccer.com/players/chad-barrett,https://www.mlssoccer.com/players/chris-armas

In [10]:
salary.previous_year[0:5]

0    2017
1    2017
2    2017
3    2017
4    2017
Name: previous_year, dtype: int64

In [11]:
df.head()

,Year,Club,url,A,FC,G,GP,GS,MINS,OFF,...,club_grouped,club,first_name,last_name,position,total_compensation,base_salary,first_name_cleaned,last_name_cleaned,urls
0,2006,Chicago Fire,https://www.mlssoccer.com/players/andy-herron,1.0,31.0,9.0,22.0,20.0,1647.0,36.0,...,CLB,CLB,Andy,Herron,F,"$148,750","$140,000",andy,herron,https://www.mlssoccer.com/players/andy-herron
1,2006,Chicago Fire,https://www.mlssoccer.com/players/brian-plotkin,1.0,10.0,1.0,14.0,4.0,526.0,1.0,...,CHI,CHI,Brian,Plotkin,M,"$30,000","$30,000",brian,plotkin,https://www.mlssoccer.com/players/brian-plotkin
2,2006,Chicago Fire,https://www.mlssoccer.com/players/calen-carr,1.0,21.0,1.0,24.0,3.0,520.0,4.0,...,CHI,CHI,Calen,Carr,F,"$50,500","$38,000",calen,carr,https://www.mlssoccer.com/players/calen-carr
3,2006,Chicago Fire,https://www.mlssoccer.com/players/chad-barrett,1.0,16.0,5.0,16.0,9.0,778.0,12.0,...,CHI,CHI,Chad,Barrett,F,"$48,713","$41,213",chad,barrett,https://www.mlssoccer.com/players/chad-barrett
4,2006,Chicago Fire,https://www.mlssoccer.com/players/chris-armas,5.0,37.0,1.0,29.0,29.0,2576.0,0.0,...,CHI,CHI,Chris,Armas,M,"$225,000","$225,000",chris,armas,https://www.mlssoccer.com/players/chris-armas

In [12]:
df.shape

(3566, 26)

In [13]:
salary.shape

(5524, 13)

In [14]:
df.isnull().sum()

Year                  0
Club                  0
url                   0
A                     0
FC                    0
G                     0
GP                    0
GS                    0
MINS                  0
OFF                   0
R                     0
SHTS                  0
SOG                   0
Y                     0
previous_year         0
season                0
club_grouped          0
club                  0
first_name            0
last_name             0
position              0
total_compensation    0
base_salary           0
first_name_cleaned    0
last_name_cleaned     0
urls                  0
dtype: int64

In [15]:
df.to_csv('df.csv')

In [17]:
# missing = [url if urls not in salary['url'] for url in stats_aggregate['url']]

SyntaxError: invalid syntax (<ipython-input-17-2f05e68f5691>, line 1)

In [18]:
stats_aggregate['url'].head()

0    https://www.mlssoccer.com/players/brian-mcbride
1       https://www.mlssoccer.com/players/eddie-pope
2     https://www.mlssoccer.com/players/jaime-moreno
3     https://www.mlssoccer.com/players/jesse-marsch
4      https://www.mlssoccer.com/players/tony-sanneh
Name: url, dtype: object

In [19]:
salary['url'].head()

0    https://www.mlssoccer.com/players/sebastian-gi...
1    https://www.mlssoccer.com/players/michael-bradley
2        https://www.mlssoccer.com/players/carlos-vela
3    https://www.mlssoccer.com/players/bastian-schw...
4    https://www.mlssoccer.com/players/giovani-dos-...
Name: url, dtype: object

In [20]:
d1 = set(stats_aggregate['url'].tolist())
d2 = set(salary['url'].tolist())

In [21]:
intr = set(d1) & set(d2)

In [25]:
missing = list(set(d2) - set(intr))